### ISSUE TITLE
nothing happens after login

### ISSUE THREAD

**Issue by mateoalleyne** [JohannesBauer97/keycloak-ionic#11]
I'm using the capacitor adapter. I initialize the Keycloak instance the same way as the example. When I hit the login button, the in-app browser opens and I login, however the onAuthSuccess method does not do anything . Also, when I try to get the userInfo and the sessionId I get undefined values. Why is this happening?

**Comment by JohannesBauer97** [comment]
I've created an example Angular project: https://github.com/JohannesBauer97/keycloak-ionic/tree/main/examples
This one works, probably you're missing sth in your implementation. I would need code from your implementation to help.
