### ISSUE TITLE
ERROR TypeError: Cannot read property 'Plugins' of undefined

### ISSUE THREAD

**Issue by santoshshinde2012** [JohannesBauer97/keycloak-ionic#8]
Trying to  create an example with this module but getting the following error 

ERROR TypeError: Cannot read property 'Plugins' of undefined

![image](https://user-images.githubusercontent.com/6427881/116267754-518e1400-a79a-11eb-913c-9cc397b0a038.png)

**Comment by okaa-pi** [comment]
Are you trying on a browser? This plugin only works inside an Android / iOS device via ``ionic capacitor run android`` for example.

**Comment by santoshshinde2012** [comment]
yes, But what about the browser?

**Comment by okaa-pi** [comment]
I didn't try it out, but I suppose you could add a check if you're in a browser init the Keycloak client with a different adapter, and if you're in a mobile app, use the capacitor adapter? 

I'm not a contributor to the project btw, just strolling by :)

**Comment by JohannesBauer97** [comment]
Hi, the browser implementation should work as described in the official docs: https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter

If not, could you please add here some code snippets about the usage?
